language: go

# Debian Jessie has Go 1.3.3, Fedora 22 has Go 1.4.3,
# Fedora 23 has Go 1.5.1
go:
  - 1.3.3
  - 1.4.3
  - 1.5.1
  - tip

install:
  - go get .

# Travis does not support FUSE, so we can't just run "go test ./..."
script:
  - go build
  - ./build.bash
  - go test ./internal/...
