language: go

# Debian Jessie has Go 1.3.3, Fedora 22 has Go 1.4.3,
# Fedora 23 has Go 1.5.1
go:
  - 1.4.3
  - 1.5.1
  - 1.6
  - tip

install:
  - go get .

script:
  - openssl version
  - go build
  - ./build.bash
  - ./test.bash

# fuse on travis
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
